name: "kernel_On_The_GO"   #Name of the workflow_file

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    name: "Build Silver-Core Kernel"
    runs-on: ubuntu-latest
    steps:
         run: |
           sudo sh build.sh
